/**
 * Bundle @ctrlc/cli into a single ESM file (dist/cli.mjs).
 *
 * Uses monorepo esbuild when present. Keeps @ctrlc/* and tsx external so
 * host TypeScript configs still load via load-config.mjs on demand.
 *
 * Usage: node packages/cli/scripts/build-cli.mjs
 *        npm run build -w @ctrlc/cli
 */

import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "..");
const ENTRY = path.join(PKG_ROOT, "src", "cli.mjs");
const OUTFILE = path.join(PKG_ROOT, "dist", "cli.mjs");

/**
 * Resolve esbuild from package, monorepo root, or walk-up node_modules.
 * @returns {typeof import("esbuild")}
 */
function loadEsbuild() {
  const require = createRequire(import.meta.url);
  try {
    return require("esbuild");
  } catch {
    // fall through
  }

  const candidates = [
    path.resolve(PKG_ROOT, "../../node_modules/esbuild"),
    path.resolve(PKG_ROOT, "../../../node_modules/esbuild"),
  ];
  for (const dir of candidates) {
    const pkgJson = path.join(dir, "package.json");
    if (!fs.existsSync(pkgJson)) continue;
    try {
      return require(dir);
    } catch {
      // try next
    }
  }

  console.error(
    "build-cli: esbuild not found. Install it at the monorepo root (npm i -D esbuild) or under @ctrlc/cli.",
  );
  process.exit(1);
}

async function main() {
  if (!fs.existsSync(ENTRY)) {
    console.error(`build-cli: missing entry ${ENTRY}`);
    process.exit(1);
  }

  const esbuild = loadEsbuild();
  fs.mkdirSync(path.dirname(OUTFILE), { recursive: true });

  try {
    await esbuild.build({
      entryPoints: [ENTRY],
      outfile: OUTFILE,
      bundle: true,
      format: "esm",
      platform: "node",
      target: "node20",
      // Keep workspace packages and tsx external (loaded at runtime).
      external: [
        "@ctrlc/core",
        "@ctrlc/capture",
        "tsx",
        "tsx/*",
        "playwright",
        "pngjs",
        "pixelmatch",
      ],
      banner: {
        js: "/* Generated by packages/cli/scripts/build-cli.mjs - do not edit */",
      },
      logLevel: "warning",
    });
  } catch (e) {
    console.error("build-cli: esbuild failed");
    console.error(String(/** @type {Error} */ (e)?.message ?? e));
    process.exit(1);
  }

  if (!fs.existsSync(OUTFILE)) {
    console.error(`build-cli: expected output missing: ${OUTFILE}`);
    process.exit(1);
  }

  const size = fs.statSync(OUTFILE).size;
  const kb = (size / 1024).toFixed(1);
  console.log(`build-cli: wrote ${path.relative(PKG_ROOT, OUTFILE)} (${kb} KB, ${size} bytes)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
